version: "3.5"

services:
    db:
        image: mysql:8.0.21
        container_name: mysql8
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - "./data:/var/lib/mysql"
        environment:
            MYSQL_USER: golang
            MYSQL_PASSWORD: welcome1
            MYSQL_DATABASE: golang
            MYSQL_ROOT_PASSWORD: welcome1
        ports:
            - "3306:3306"
